import type { StrategyRules } from "./types";

export function generatePineScript(strategy: StrategyRules): string {
  const lines: string[] = [];

  lines.push(`// ${strategy.name}`);
  lines.push(`// ${strategy.description}`);
  lines.push(`// Generated by CryptoLens - Educational use only`);
  lines.push(``);
  lines.push(`//@version=5`);
  lines.push(
    `strategy("${strategy.name}", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=100)`
  );
  lines.push(``);

  // ── Inputs ──
  lines.push(`// ── Inputs ──`);
  lines.push(
    `rsiLen       = input.int(14, "RSI Length")`
  );
  lines.push(
    `rsiOversold  = input.float(${strategy.rsiOversold}, "RSI Oversold")`
  );
  lines.push(
    `rsiOverbought = input.float(${strategy.rsiOverbought}, "RSI Overbought")`
  );

  if (strategy.useSMACross) {
    lines.push(`smaFast      = input.int(20, "SMA Fast Length")`);
    lines.push(`smaSlow      = input.int(50, "SMA Slow Length")`);
  }

  if (strategy.useMACDCross) {
    lines.push(`macdFast     = input.int(12, "MACD Fast")`);
    lines.push(`macdSlow     = input.int(26, "MACD Slow")`);
    lines.push(`macdSignal   = input.int(9, "MACD Signal")`);
  }

  if (strategy.useBollingerBounce) {
    lines.push(`bbLen        = input.int(20, "Bollinger Length")`);
    lines.push(`bbMult       = input.float(2.0, "Bollinger StdDev")`);
  }

  lines.push(
    `stopLossPct  = input.float(${strategy.stopLossPercent}, "Stop Loss %") / 100`
  );
  lines.push(
    `takeProfitPct = input.float(${strategy.takeProfitPercent}, "Take Profit %") / 100`
  );
  lines.push(``);

  // ── Indicators ──
  lines.push(`// ── Indicators ──`);
  lines.push(`rsiVal = ta.rsi(close, rsiLen)`);

  if (strategy.useSMACross) {
    lines.push(`sma20 = ta.sma(close, smaFast)`);
    lines.push(`sma50 = ta.sma(close, smaSlow)`);
  }

  if (strategy.useMACDCross) {
    lines.push(
      `[macdLine, signalLine, _] = ta.macd(close, macdFast, macdSlow, macdSignal)`
    );
  }

  if (strategy.useBollingerBounce) {
    lines.push(`[bbMiddle, bbUpper, bbLower] = ta.bb(close, bbLen, bbMult)`);
  }

  lines.push(``);

  // ── Entry Conditions ──
  lines.push(`// ── Entry Conditions ──`);
  const entryConditions: string[] = [];

  entryConditions.push(`rsiEntry = rsiVal <= rsiOversold`);

  if (strategy.useSMACross) {
    entryConditions.push(
      `smaCross = ta.crossover(sma20, sma50)`
    );
  }

  if (strategy.useMACDCross) {
    entryConditions.push(
      `macdCross = ta.crossover(macdLine, signalLine)`
    );
  }

  if (strategy.useBollingerBounce) {
    entryConditions.push(`bbBounce = close <= bbLower`);
  }

  for (const c of entryConditions) {
    lines.push(c);
  }

  // Combine entry: any condition triggers
  const entryNames = ["rsiEntry"];
  if (strategy.useSMACross) entryNames.push("smaCross");
  if (strategy.useMACDCross) entryNames.push("macdCross");
  if (strategy.useBollingerBounce) entryNames.push("bbBounce");

  lines.push(`enterLong = ${entryNames.join(" or ")}`);
  lines.push(``);

  // ── Exit Conditions ──
  lines.push(`// ── Exit Conditions ──`);
  const exitConditions: string[] = [];

  exitConditions.push(`rsiExit = rsiVal >= rsiOverbought`);

  if (strategy.useSMACross) {
    exitConditions.push(
      `smaDeathCross = ta.crossunder(sma20, sma50)`
    );
  }

  if (strategy.useMACDCross) {
    exitConditions.push(
      `macdBearCross = ta.crossunder(macdLine, signalLine)`
    );
  }

  for (const c of exitConditions) {
    lines.push(c);
  }

  const exitNames = ["rsiExit"];
  if (strategy.useSMACross) exitNames.push("smaDeathCross");
  if (strategy.useMACDCross) exitNames.push("macdBearCross");

  lines.push(`exitLong = ${exitNames.join(" or ")}`);
  lines.push(``);

  // ── Strategy Execution ──
  lines.push(`// ── Strategy Execution ──`);
  lines.push(`if enterLong`);
  lines.push(`    strategy.entry("Long", strategy.long)`);
  lines.push(``);
  lines.push(`if exitLong`);
  lines.push(`    strategy.close("Long")`);
  lines.push(``);

  // Stop loss and take profit
  lines.push(`// ── Risk Management ──`);
  lines.push(`if strategy.position_size > 0`);
  lines.push(
    `    strategy.exit("SL/TP", "Long", stop=strategy.position_avg_price * (1 - stopLossPct), limit=strategy.position_avg_price * (1 + takeProfitPct))`
  );
  lines.push(``);

  // ── Plots ──
  lines.push(`// ── Plots ──`);

  if (strategy.useSMACross) {
    lines.push(
      `plot(sma20, "SMA 20", color=color.new(color.white, 50))`
    );
    lines.push(
      `plot(sma50, "SMA 50", color=color.new(color.gray, 50))`
    );
  }

  if (strategy.useBollingerBounce) {
    lines.push(
      `plot(bbUpper, "BB Upper", color=color.new(color.gray, 70))`
    );
    lines.push(
      `plot(bbLower, "BB Lower", color=color.new(color.gray, 70))`
    );
  }

  lines.push(
    `plotshape(enterLong, "Buy", shape.triangleup, location.belowbar, color.new(color.green, 0), size=size.small)`
  );
  lines.push(
    `plotshape(exitLong, "Sell", shape.triangledown, location.abovebar, color.new(color.red, 0), size=size.small)`
  );

  return lines.join("\n");
}
